### ISSUE TITLE
wrong username and password will cause Internal Server Error

### ISSUE THREAD

**Issue by beta4better** [bitrot/simple-multiblog#12]
Traceback (most recent call last):
  File "/home/beta4better/venvs/simple-multiblog/lib/python2.6/site-packages/gunicorn/workers/sync.py", line 99, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/beta4better/venvs/simple-multiblog/lib/python2.6/site-packages/flask/app.py", line 1518, in **call**
    return self.wsgi_app(environ, start_response)
  File "/home/beta4better/venvs/simple-multiblog/lib/python2.6/site-packages/flask/app.py", line 1506, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/beta4better/venvs/simple-multiblog/lib/python2.6/site-packages/flask/app.py", line 1504, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/beta4better/venvs/simple-multiblog/lib/python2.6/site-packages/flask/app.py", line 1264, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/beta4better/venvs/simple-multiblog/lib/python2.6/site-packages/flask/app.py", line 1262, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/beta4better/venvs/simple-multiblog/lib/python2.6/site-packages/flask/app.py", line 1248, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/beta4better/simple-multiblog/simple.py", line 54, in _auth_decorator
    if not check_password_hash(author.password, auth.password):
AttributeError: 'NoneType' object has no attribute 'password'

**Comment by ehaughee** [comment]
Do you get a 404 HTTP response as well?  That is what I get from a superficial test (I am not in a position to check the logs right this second).  A 404 is not the correct response either so this definitely needs to be looked at.  Thanks for submitting the issue!

**Comment by ehaughee** [comment]
Do a pull for the latest changes, I believe it is fixed.  I added `if not author or not check_password(...` to the check.  We thought (and obviously didn't test :P) that SQLAlchemy threw a minor exception when no records were found.  Apparently this is not the case in all (maybe any) scenarios.

**Comment by rmacy** [comment]
Hmm, I thought we had fixed that a long time ago. Thanks for bringing it to our attention!

**Comment by ehaughee** [comment]
@rmacy I am waiting for him to respond that it does indeed fix his issue.  I probably should have closed it with the commit and `closes #12` but I had no idea you could do that haha.

**Comment by rmacy** [comment]
@ehaughee A bug I had noticed, and that I thought I fixed, a long time ago, was that if you submit nothing in the user and/or password fields you would get a nonetype has no attribute (pass/user) exception thrown. Was this the same?

**Comment by ehaughee** [comment]
@rmacy Nothing works fine although I may not have tested it before I added that additional check.  I can't remember.  I am just going to close this issue.  He can reopen it if need be.

Closed by [52e8afda39](https://github.com/bitrot/simple-multiblog/commit/52e8afda39e97623c42233f4d30dc0eaa841756f)
